name: build and test
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: golang:1.18-bullseye

    services:
      singlestore:
        # check for new versions at https://hub.docker.com/r/singlestore/cluster-in-a-box/tags
        image: singlestore/cluster-in-a-box:alma-7.8.2-8c7b918527-4.0.5-1.13.6
        env:
          LICENSE_KEY: ${{ secrets.SINGLESTORE_LICENSE }}
          ROOT_PASSWORD: "test"
          START_AFTER_INIT: "Y"

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.18"
      - run: >
          until mysql -h singlestore -u root -ptest -e "select 1"; do
            echo "waiting for mysql..."
            sleep 1
          done
      - run: docker logs $(docker ps -ql)
      - run: mysql -h singlestore -u root -ptest <schema.sql <procedures.sql
      - run: go test -config config.github.toml
